---
- connection: local
  hosts: 127.0.0.1
  tasks:
    - name: Get the username running the deploy
      local_action: command whoami
      register: running_user_cmd
    - name: Set username fact
      set_fact:
        running_user: "{{ running_user_cmd.stdout }}"
    - name: "Create ~/bin/"
      file:
        name: "~/bin/"
        state: directory
    - name: "Set up iTerm shell integrations"
      get_url:
        dest: ~/.iterm2_shell_integration.zsh
        url: https://iterm2.com/misc/zsh_startup.in
    - name: "Set up .zshrc"
      template:
        src: "zshrc.j2"
        dest: "~/.zshrc"
    - name: "Set up Git global ignores"
      copy:
        src: "global-gitignore"
        dest: "~/.gitignore"
    - name: "Add dns reset script"
      copy:
        src: "scripts/flush-dns-cache.sh"
        dest: "~/bin/flush-dns-cache"
        mode: 0755
    - name: "Copy iTerm Colors"
      copy:
        src: "default.itermcolors"
        dest: "~/default.itermcolors"
    - name: Set up Visual Studio Code Settings
      copy:
        src: "vscode/settings.json"
        dest: "~/Library/Application Support/Code/User/settings.json"
    - name: Add Atom Packages
      synchronize:
        src: "atom/packages"
        dest: "~/.atom/"
    - name: Set up Atom Settings
      copy:
        src: "atom/config/"
        dest: "~/.atom/"
...
