---
- connection: local
  hosts: 127.0.0.1
  tasks:
    - name: Get the username running the deploy
      local_action: command whoami
      register: running_user_cmd
    - name: Set username fact
      set_fact:
        running_user: "{{ running_user_cmd.stdout }}"
    - name: "Create base directories"
      file:
        name: "{{ item }}"
        state: directory
      with_items:
        - "~/bin/"
        - "~/.ssh/"
        - "~/Documents/projects"
    - name: "Set up iTerm shell integrations"
      get_url:
        dest: ~/.iterm2_shell_integration.zsh
        url: https://iterm2.com/misc/zsh_startup.in
    - name: "Copy iTerm Colors"
      copy:
        src: "default.itermcolors"
        dest: "~/default.itermcolors"
    - name: "Copy iTerm Settings"
      copy:
        src: "com.googlecode.iterm2.plist"
        dest: "~/com.googlecode.iterm2.plist"
    - name: "Set up .zshrc"
      template:
        src: "zshrc.j2"
        dest: "~/.zshrc"
    - name: "Set up .p10k.zsh"
      copy:
        src: "p10k.zsh"
        dest: "~/.p10k.zsh"
    - name: "Set up SSH config"
      copy:
        src: "ssh-config"
        dest: "~/.ssh/config"
    - name: "Configure SSH key"
      openssh_keypair:
        path: "~/.ssh/id_ecdsa"
        type: "ecdsa"
    - name: "Set up Git config"
      copy:
        src: "git-config"
        dest: "~/.gitconfig"
    - name: "Set up Git global ignores"
      copy:
        src: "global-gitignore"
        dest: "~/.gitignore"
    - name: "Download powerlevel10k zsh theme"
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1
    - name: "Add dns reset script"
      copy:
        src: "scripts/flush-dns-cache.sh"
        dest: "~/bin/flush-dns-cache"
        mode: 0755
    - name: "Set up backup script"
      copy:
        src: "scripts/home_dir_backup.sh"
        dest: "~/home_dir_backup.sh"
        mode: 0755
    - name: Set up Visual Studio Code Settings
      copy:
        src: "vscode/settings.json"
        dest: "~/Library/Application Support/Code/User/settings.json"
    - name: Add Atom Packages
      synchronize:
        src: "atom/packages"
        dest: "~/.atom/"
    - name: Set up Atom Settings
      copy:
        src: "atom/config/"
        dest: "~/.atom/"
...
