---
- connection: local
  hosts: 127.0.0.1
  tasks:
    - name: "Install homebrew packages"
      homebrew:
        state: present
        name:
          - git
          - go
          - htop
          - hugo
          - kubectx
          - kubernetes-cli
          - mas
          - mkcert
          - screenresolution
          - watch
    - name: "Install fonts homebrew tap"
      homebrew_tap:
        name: "homebrew/cask-fonts"
    - name: "Install homebrew casks"
      homebrew_cask:
        state: present
        name:
          # apps
          - backblaze
          - bettertouchtool
          - doxie
          - flux
          - goland
          - google-chrome
          - iterm2
          - postman
          - spectacle
          - spotify
          - sublime-text
          - visual-studio-code
          - zoom
          # fonts
          - font-hack
          - font-meslo-lg-nerd-font
      ignore_errors: yes
    - name: "Install App Store applications"
      shell:
        cmd: "mas install {{ item }}"
      with_items:
        - 1365531024 # 1blocker
        - 824171161  # affinity designer
        - 824183456  # affinity photo
        - 881418622  # affinity publisher
        - 611658502  # boxy svg
        - 411643860  # daisy disk
        - 1505779553 # dashlane for safari
        - 1127253508 # dr unarchiver
        - 524141863  # jump desktop
        - 1124615151 # home inventory
        - 587512244  # kaleidoscope
        - 409183694  # keynote
        - 405399194  # kindle
        - 465965038  # markdown pro
        - 969978718  # noiseless
        - 409203825  # numbers
        - 711830901  # omnigraffle
        - 1040002810 # omniplan
        - 409201541  # pages
        - 1289583905 # pixelmator pro
        - 498370702  # regex rx
        - 803453959  # slack
        - 1176895641 # spark
        - 1058362543 # swift publisher
        - 960276676  # taurine
        - 904280696  # things
        - 403388562  # transmit
        - 497799835  # xcode
      ignore_errors: yes
    - name: "Install xcode tools for delve"
      shell:
        cmd: "xcode-select --install"
      ignore_errors: yes
...
